#!/bin/sh

exec 2>&1
sv check dbus > /dev/null || exit 1

[ -d /run/wayland ] || mkdir -p /run/wayland
chmod 0700 /run/wayland

export XDG_RUNTIME_DIR="/run/wayland/"

exec /usr/bin/weston --tty=4 --config=/etc/weston/weston.ini > /dev/null 2>&1
