#!/bin/sh
set -e

PARTITION="/dev/settings"
MOUNT="/mnt"

if ! /sbin/grep -q "${PARTITION}" /proc/mounts; then
  /sbin/mkfs.ext4 ${PARTITION} -L settings -F

  /sbin/mount -t ext4 -o rw ${PARTITION} ${MOUNT}

  /sbin/chmod 755 -R ${MOUNT}

  /sbin/sync

  /sbin/umount ${MOUNT}

  echo "${PARTITION} was reset successfully."
else
  echo "${PARTITION} is mounted, exiting..."
  exit 1
fi
