// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OtaError, OtaKind, OtaProgress, RangePart, RangeSpec } from "./shared";
import type { MsgMeta, WireError } from "./wire";

export type GatewayToNocturneMsg = { id: string, meta: MsgMeta, data: GatewayToNocturneMsgData, };

export type GatewayToNocturneMsgData = { "type": "system", "data": GatewayToNocturneSystemMsg } | { "type": "error", "data": WireError };

export type GatewayToNocturneSystemMsg = { "event": "otaBegin", "data": OtaBegin } | { "event": "otaChunk", "data": OtaChunk } | { "event": "otaAbandon", "data": OtaAbandon } | { "event": "otaAssetRangeReply", "data": OtaAssetRangeReply } | { "event": "otaAssetRangeRejected", "data": OtaAssetRangeRejected } | { "event": "otaAssetRangeChunk", "data": OtaAssetRangeChunk };

export type NocturneToGatewayMsg = { id: string, meta: MsgMeta, data: NocturneToGatewayMsgData, };

export type NocturneToGatewayMsgData = { "type": "system", "data": NocturneToGatewaySystemMsg } | { "type": "error", "data": WireError } | { "type": "ack" } | { "type": "done" };

export type NocturneToGatewaySystemMsg = { "event": "otaProgress", "data": OtaProgress } | { "event": "otaError", "data": OtaError } | { "event": "otaBeginAck", "data": OtaBeginAck } | { "event": "otaBeginRejected", "data": OtaBeginRejected } | { "event": "otaAssetRange", "data": OtaAssetRange } | { "event": "otaAssetRangeAbandon", "data": OtaAssetRangeAbandon };

export type OtaAbandon = { updateId: string, };

export type OtaAssetRange = { updateId: string, asset: string, ranges: Array<RangeSpec>, };

export type OtaAssetRangeAbandon = { requestId: string, };

export type OtaAssetRangeChunk = { requestId: string, partIndex: number, offset: number, bytes: Uint8Array, last: boolean, };

export type OtaAssetRangeRejected = { reason: string, };

export type OtaAssetRangeReply = { totalSize: number, parts: Array<RangePart>, };

export type OtaBegin = { kind: OtaKind, updateId: string, updateUrlBase: string | null, expectedSha256: string, expectedSize: number, };

export type OtaBeginAck = { resumeFromOffset: number, };

export type OtaBeginRejected = { reason: string, };

export type OtaChunk = { updateId: string, offset: number, bytes: Uint8Array, last: boolean, };
