// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MsgMeta = { "kind": "command" } | { "kind": "event" } | {
  "kind": "request";
} | { "kind": "response"; "data": ResponseMeta };

export type ResponseMeta = { requestId: string };

export type WireError =
  | { "type": "unsupported" }
  | { "type": "unimplemented" }
  | { "type": "malformed"; "data": { reason: string } }
  | { "type": "handlerFailed"; "data": { reason: string } };
