#!/usr/bin/env bash

# Sets up a raspberry pi to provide internet for USB device connected
# This should be run ONCE on the host machine

set -e  # bail on any errors

#Set terminal as non-interactive
export DEBIAN_FRONTEND=noninteractive

# VARIABLES
HOST_NAME="superbird"
USBNET_PREFIX="192.168.7"  # usb network will use .1 as host device, and .2 for superbird
CT_INTERFACE="usb0"
WAN_INTERFACE="wlan0"

# FUNCTIONS

function remove_if_exists() {
    # remove a file if it exists
    FILEPATH="$1"
    if [ -f "$FILEPATH" ]; then
        echo "found ${FILEPATH}, removing"
        rm "$FILEPATH"
    fi
}

function append_if_missing() {
    # append string to file only if it does not already exist in the file
    STRING="$1"
    FILEPATH="$2"
    grep -q "$STRING" "$FILEPATH" || {
        echo "appending \"$STRING\" to $FILEPATH"
        echo "$STRING" >> "$FILEPATH"
        return 1
    }
    echo "Already found \"$STRING\" in $FILEPATH"
    return 0
}

function forward_port() {
    # usage: forward_port <host port> <superbird port>
    # forward a tcp port to access service on superbird via host
    #   if no superbird port is provided, same port number is used for both
    SOURCE="$1"
    DEST="$2"
    if [ -z "$DEST" ]; then
        DEST="$SOURCE"
    fi
    iptables -t nat -A PREROUTING -p tcp -i "${WAN_INTERFACE}" --dport "$SOURCE" -j DNAT --to-destination "${USBNET_PREFIX}.2:$DEST"
    iptables -A FORWARD -p tcp -d "${USBNET_PREFIX}.2" --dport "$DEST" -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
}

# PRE_FLIGHT_CHECKS

# Need to be root
if [ "$(id -u)" != "0" ]; then
    echo "Must be run as root"
    exit 1
fi

# Does not run on BSD
if [ "$(uname -s)" != "Linux" ]; then
    echo "Only works on Linux!"
    exit 1
fi

# Detect if usb0 CarThing NIC is already configured.
if ! ip addr show "${CT_INTERFACE}" | grep -q "inet "; then
    echo "No inactive network interface found. This may occur if the script was already run, or if your Spotify Car Thing is not plugged in."
    exit 1
fi

# Detect if car thing is plugged in
if lsusb | grep -q "Google Inc."
then
    echo "Car Thing detected, proceeding with setup"
else
    echo "Car Thing not detected. Please plug in the Car Thing and try again"
    exit 1
fi

# MAIN_SCRIPT

# Fix usb enumeration when connecting superbird in maskroom mode
echo '# Amlogic S905 series can be booted up in Maskrom Mode, and it needs a rule to show up correctly' > /etc/udev/rules.d/70-carthing-maskrom-mode.rules
echo 'SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ATTR{idVendor}=="1b8e", ATTR{idProduct}=="c003", MODE:="0666", SYMLINK+="worldcup"' >> /etc/udev/rules.d/70-carthing-maskrom-mode.rules

# Prevent systemd / udev from renaming usb network devices by mac address
remove_if_exists /lib/systemd/network/73-usb-net-by-mac.link
remove_if_exists /lib/udev/rules.d/73-usb-net-by-mac.rules

# Allow IP forwarding
append_if_missing "net.ipv4.ip_forward = 1" /etc/sysctl.conf || {
    sysctl -p  # reload from conf
}

# Forwarding rules
mkdir -p /etc/iptables

# Clear all iptables rules
iptables -F
iptables -X
iptables -Z 
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -t raw -F
iptables -t raw -X

# Rewrite iptables rules
iptables -P FORWARD ACCEPT
iptables -A FORWARD -o "${WAN_INTERFACE}" -i "${CT_INTERFACE}" -s "${USBNET_PREFIX}.0/24" -m conntrack --ctstate NEW -j ACCEPT
iptables -A FORWARD -o "${WAN_INTERFACE}" -i "${CT_INTERFACE}" -s "${USBNET_PREFIX}.0/24" -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -A POSTROUTING -t nat -j MASQUERADE -s "${USBNET_PREFIX}.0/24"

# persist rules to file
iptables-save > /etc/iptables/rules.v4

# write the usb network config
mkdir -p /etc/network/interfaces.d/

cat << EOF > /etc/network/interfaces.d/usb0
# generated by $0
allow-hotplug usb0
iface usb0 inet static
	address ${USBNET_PREFIX}.1
	netmask 255.255.255.0
EOF

# add superbird to /etc/hosts
append_if_missing "${USBNET_PREFIX}.2  ${HOST_NAME}"  "/etc/hosts"

echo "Need to reboot for all changes to take effect!"

exit 0