// THIS FILE IS GENERATED BY tools/codegen. Do not edit by hand.
// Re-generate with `just codegen`.

// Hand-written csm::* modules remain authoritative. Import this module explicitly while migrating CSMs from inventory entries.

use bytes::Bytes;
use serde::{Deserialize, Serialize};

pub const SENT_BY_ACCESSORY: &[u16] = &[
    AuthenticationCertificate::CSM_MSG_ID,
    AuthenticationResponse::CSM_MSG_ID,
];
pub const RECEIVED_BY_ACCESSORY: &[u16] = &[
    RequestAuthenticationCertificate::CSM_MSG_ID,
    RequestAuthenticationChallengeResponse::CSM_MSG_ID,
    AuthenticationFailed::CSM_MSG_ID,
    AuthenticationSucceeded::CSM_MSG_ID,
    StartIdentification::CSM_MSG_ID,
    IdentificationAccepted::CSM_MSG_ID,
    DeviceInformationUpdate::CSM_MSG_ID,
    DeviceLanguageUpdate::CSM_MSG_ID,
    DeviceTimeUpdate::CSM_MSG_ID,
    DeviceUUIDUpdate::CSM_MSG_ID,
];

/// Device asks the accessory for its MFi authentication certificate.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, iap2_macros::Csm)]
#[csm(id = 0xAA00)]
pub struct RequestAuthenticationCertificate {}

/// Accessory returns its MFi authentication certificate.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, iap2_macros::Csm)]
#[csm(id = 0xAA01)]
pub struct AuthenticationCertificate {
    /// X.509 DER certificate read from the MFi coprocessor.
    #[csm(param = 0)]
    pub cert: Bytes,
}

/// Device asks the accessory to sign an authentication challenge.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, iap2_macros::Csm)]
#[csm(id = 0xAA02)]
pub struct RequestAuthenticationChallengeResponse {
    /// Challenge bytes the accessory signs with the MFi coprocessor.
    #[csm(param = 0)]
    pub challenge: Bytes,
}

/// Accessory returns the signed MFi challenge response.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, iap2_macros::Csm)]
#[csm(id = 0xAA03)]
pub struct AuthenticationResponse {
    /// Signed challenge response returned by the MFi coprocessor.
    #[csm(param = 0)]
    pub response: Bytes,
}

/// Device reports that MFi authentication failed.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, iap2_macros::Csm)]
#[csm(id = 0xAA04)]
pub struct AuthenticationFailed {}

/// Device reports that MFi authentication succeeded.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, iap2_macros::Csm)]
#[csm(id = 0xAA05)]
pub struct AuthenticationSucceeded {}

/// Device starts the iAP2 identification exchange.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, iap2_macros::Csm)]
#[csm(id = 0x1D00)]
pub struct StartIdentification {}

/// Device accepts the accessory's identification information.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, iap2_macros::Csm)]
#[csm(id = 0x1D02)]
pub struct IdentificationAccepted {}

/// Device pushes its user-visible name after subscription.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, iap2_macros::Csm)]
#[csm(id = 0x4E09)]
pub struct DeviceInformationUpdate {
    /// User-visible device name.
    #[csm(param = 0)]
    pub device_name: String,
}

/// Device pushes its current language after subscription.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, iap2_macros::Csm)]
#[csm(id = 0x4E0A)]
pub struct DeviceLanguageUpdate {
    /// ISO 639 language code.
    #[csm(param = 0)]
    pub language: String,
}

/// Device pushes wall-clock and timezone-offset state after subscription.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, iap2_macros::Csm)]
#[csm(id = 0x4E0B)]
pub struct DeviceTimeUpdate {
    /// Unix-epoch seconds.
    #[csm(param = 0)]
    pub seconds_since_reference_date: i64,
    /// Signed timezone offset from GMT in minutes.
    #[csm(param = 1)]
    pub tz_offset_minutes: i16,
    /// Signed daylight-saving offset in minutes.
    #[csm(param = 2)]
    pub dst_offset_minutes: i8,
}

/// Device pushes its stable UUID after subscription.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, iap2_macros::Csm)]
#[csm(id = 0x4E0C)]
pub struct DeviceUUIDUpdate {
    /// Stable per-device UUID string.
    #[csm(param = 0)]
    pub uuid: String,
}
