BBPATH .= ":${LAYERDIR}"
NOCTURNE_LAYERDIR := "${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "nocturne"
BBFILE_PATTERN_nocturne = "^${LAYERDIR}/"
BBFILE_PRIORITY_nocturne = "20"

LAYERSERIES_COMPAT_nocturne = "scarthgap wrynose"

LAYERDEPENDS_nocturne = "core superbird"
