# Nocturne directory layout.
#
# /var/nocturne/                  user-installable webapp bundles on data partition.
# /var/lib/nocturne/state/        persistent daemon state on the data partition.
#                                 This state is shared between system_a and system_b
#                                 so it survives bootslot swaps and OTA upgrades.

d /var/nocturne                 0755 root root - -
d /var/nocturne/webapps         0755 root root - -
d /var/lib/nocturne             0755 root root - -
d /var/lib/nocturne/state       0755 root root - -
