require conf/distro/superbird.conf

DISTRO = "nocturne"
DISTRO_NAME = "Nocturne"
DISTRO_VERSION = "4.0.5"
MAINTAINER = "Nocturne Team <hello@usenocturne.com>"

SUPERBIRD_HOSTNAME = "nocturne"
SUPERBIRD_MDNS_SERVICE_NAME = "Nocturne"
SUPERBIRD_USB_GADGET_NAME = "nocturne"
SUPERBIRD_USB_GADGET_MANUFACTURER = "Vanta Labs"
SUPERBIRD_USB_GADGET_PRODUCT = "Nocturne for Spotify Car Thing"
SUPERBIRD_BOOT_LOGO_NAME = "nocturne-bootup.bmp"
SUPERBIRD_WESTON_SPLASH_IMAGE = "nocturne-splash.png"

CHROMIUM_KIOSK_URL = "http://127.0.0.1:8080/"